# Site Settings
title: Qiyu's Pages
description:
author: Qiyu
resume_url: /CV.pdf
linkedin_url: https://www.linkedin.com/in/qiyuw/
google_url: https://scholar.google.com/citations?user=oDn0AnwAAAAJ
show_downloads: True
logo: /favicon.ico
portrait: /portrait.jpg
# Website identifier from the MapMyVisitors globe embed code.
mapmyvisitors_token: Wj6cagaVFNRkupewF32T5F0kYLUiCyi9ykTSpg6Q6No
mapmyvisitors_stats_url: https://mapmyvisitors.com/web/1c8nl


# theme
theme: jekyll-theme-minimal
