# Site Settings
title: Qiyu's Pages
description:
author: Qiyu
resume_url: /CV.pdf
linkedin_url: https://www.linkedin.com/in/qiyuw/
google_url: https://scholar.google.com/citations?user=oDn0AnwAAAAJ
show_downloads: True
logo: /favicon.ico
portrait: /portrait.jpg
clustrmaps_token: gX26Gy4zINxbjRxawqAoxCeb2K_L3W8XCPWN-IeK5KA


# theme
theme: jekyll-theme-minimal
